### ISSUE TITLE
Make available on Hombrew

### ISSUE THREAD

**Issue by dkanejs** [Ullaakut/astronomer#46]
After I seen astronomer on [HN](https://news.ycombinator.com/item?id=20473871) I put together this homebrew tap to ease installation on OSX: https://github.com/dkanejs/homebrew-astronomer

It would be cool to get this into the official Homebrew itself or have you as the maintainer of the tap under your own GitHub namespace, this way you can also update the formulae with each release 👍 

What do you think?

**Comment by Ullaakut** [comment]
I'm fine with you being the maintainer of the tap if you're okay with it, I would gladly document it in the readme, but if you want I can do one as well and maintain it 👍 

What sounds better for you? :)

**Comment by dkanejs** [comment]
I'm happy to maintain. 

If that changes (or if the community feels different in the future) for whatever reason we can migrate it over, etc 👍

It's a quick thing anyway 😄

**Comment by Ullaakut** [comment]
I will document it then, thanks :)
