### ISSUE TITLE
Code Reviews / Pull Requests

### ISSUE THREAD

**Issue by jasperblues** [Ullaakut/astronomer#84]
Hello. Nice project. I ran it on appsquickly/typhoon, which is a still active, but slowly being sunsetted. 

Was surprised that it only reported a 'B' score. Report as follows: 

```
Beginning fetching process for repository appsquickly/Typhoon
Pre-fetching all stargazers...ok
  > Selecting 200 first stargazers out of 2656
  > Selecting 800 random stargazers out of 2656
Fetching contributions for 1000 users up to year 2013
Building trust report...ok

Averages                             Score           Trust
--------                             -----           -----
Weighted contributions:              20234             B
Private contributions:               447               A
Created issues:                      12                C
Commits authored:                    227               C
Repositories:                        40                A
Pull requests:                       10                D
Code reviews:                        2                 E
Account age (days):                  2275              A
5th percentile:                      26                A
10th percentile:                     70                A
15th percentile:                     106               A
20th percentile:                     192               A
25th percentile:                     313               A
30th percentile:                     495               A
35th percentile:                     626               A
40th percentile:                     968               A
45th percentile:                     1181              A
50th percentile:                     1470              A
55th percentile:                     2192              A
60th percentile:                     2586              B
65th percentile:                     3969              B
70th percentile:                     5271              B
75th percentile:                     7115              B
80th percentile:                     10357             B
85th percentile:                     14953             C
90th percentile:                     34799             A
95th percentile:                     135676            A
----------------------------------------------------------
Overall trust:                                         B

✔ Analysis successful. 1000 users computed.
```

What does the pull-requests metric mean? The project didn't have many pull requests? Or the users who started the project don't make many? 

I gave trusted committers push access. <-- Maybe this is useful? 

Again does that mean the users who starred the repo didn't do code reviews, or that we didn't? 

Just sharing some #random feedback. Please close this issue once received. Again, very nice project.

**Comment by Ullaakut** [comment]
Yes, it uses the average GitHub metrics of people who starred the project. What this means here is that the users who starred the project are not power users of GitHub and that on average they have opened a low amount of pull requests.

It seems to me like the reason behind the `B` rating comes from the fact that since it is _being sunsetted_ as you said, its average stargazers might be old accounts that have been abandoned. Another possibility is that its target demographic (OSX/iOS developers) might not tend to be the biggest contributors to open source software on average.

There are many factors to take into account, but overall, don't worry, a `B` rating is fine :)

**Comment by jasperblues** [comment]
Thank you for the info!
